In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
boston_data =keras.datasets.boston_housing

In [3]:
(x_train,y_train),(x_test,y_test) = boston_data.load_data()

In [4]:
len(x_train),len(y_train),len(x_test),len(y_test)

(404, 404, 102, 102)

In [5]:
x_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

In [7]:
x_train = np.array(x_train)
x_test = np.array(x_test)

In [8]:
x_train

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [9]:
x_train[:,0].max()

88.9762

In [10]:
for i in range(13):
    print(i)
    x_train[:,i] = (x_train[:,i]-x_train[:,i].min())/(x_train[:,i].max()-x_train[:,i].min())
    x_test[:,i] = (x_test[:,i]-x_test[:,i].min())/(x_test[:,i].max()-x_test[:,i].min())

0
1
2
3
4
5
6
7
8
9
10
11
12


In [11]:
x_train[0],x_test[0]

(array([0.01378163, 0.        , 0.28152493, 0.        , 0.31481481,
        0.49980635, 0.91452111, 0.29719123, 0.13043478, 0.22753346,
        0.89361702, 1.        , 0.46881898]),
 array([0.72190697, 0.        , 0.63650075, 0.        , 0.59916493,
        0.39846154, 1.        , 0.0346309 , 1.        , 0.91412214,
        0.87804878, 0.00698455, 0.90222813]))

In [12]:
model =  keras.Sequential([
    keras.layers.Dense(64,activation='relu',input_shape=(13,)),
    keras.layers.Dense(1,activation='linear')
])

model.summary()
model.compile(loss='mse',
             optimizer='sgd')
model.fit(x_train,y_train,epochs=200)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                896       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________
Epoch 1/200
13/13 [==============================] - 0s 2ms/step - loss: 171.0585
Epoch 2/200
13/13 [==============================] - 0s 3ms/step - loss: 56.6921
Epoch 3/200
13/13 [==============================] - 0s 2ms/step - loss: 49.3105
Epoch 4/200
13/13 [==============================] - 0s 3ms/step - loss: 39.3294
Epoch 5/200
13/13 [==============================] - 0s 1ms/step - loss: 40.3684
Epoch 6/200
13/13 [==============================] - 0s 2ms/step - loss: 50.0409
Epoch 7/200
13/13 [==============

13/13 [==============================] - 0s 1ms/step - loss: 11.9159
Epoch 94/200
13/13 [==============================] - 0s 1ms/step - loss: 11.3898
Epoch 95/200
13/13 [==============================] - 0s 1ms/step - loss: 12.1747
Epoch 96/200
13/13 [==============================] - 0s 880us/step - loss: 12.1288
Epoch 97/200
13/13 [==============================] - 0s 939us/step - loss: 11.3233
Epoch 98/200
13/13 [==============================] - 0s 1ms/step - loss: 12.3979
Epoch 99/200
13/13 [==============================] - 0s 1ms/step - loss: 9.6498
Epoch 100/200
13/13 [==============================] - 0s 1ms/step - loss: 12.7614
Epoch 101/200
13/13 [==============================] - 0s 757us/step - loss: 12.1581
Epoch 102/200
13/13 [==============================] - 0s 858us/step - loss: 9.8178
Epoch 103/200
13/13 [==============================] - 0s 962us/step - loss: 18.9413
Epoch 104/200
13/13 [==============================] - 0s 1ms/step - loss: 11.3303
Epoch 105/200
13

13/13 [==============================] - 0s 2ms/step - loss: 7.7124
Epoch 193/200
13/13 [==============================] - 0s 1ms/step - loss: 7.9486
Epoch 194/200
13/13 [==============================] - 0s 1ms/step - loss: 8.2949
Epoch 195/200
13/13 [==============================] - 0s 770us/step - loss: 7.1109
Epoch 196/200
13/13 [==============================] - 0s 1ms/step - loss: 7.2136
Epoch 197/200
13/13 [==============================] - 0s 1ms/step - loss: 7.4228
Epoch 198/200
13/13 [==============================] - 0s 995us/step - loss: 10.4782
Epoch 199/200
13/13 [==============================] - 0s 1ms/step - loss: 7.5637
Epoch 200/200
13/13 [==============================] - 0s 814us/step - loss: 7.4864


In [13]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 1ms/step - loss: 34.2408


34.240753173828125

In [14]:
x_test[0:1]

array([[0.72190697, 0.        , 0.63650075, 0.        , 0.59916493,
        0.39846154, 1.        , 0.0346309 , 1.        , 0.91412214,
        0.87804878, 0.00698455, 0.90222813]])

In [15]:
for i in range(100):
    print("预测：",model.predict(x_test[i:i+1])[0],"实际：",y_test[i:i+1],'差值：',
         abs(model.predict(x_test[i:i+1])[0][0]-y_test[i:i+1][0]),'误差占比：',
         str(round(100*abs(model.predict(x_test[i:i+1])[0][0]-y_test[i:i+1][0])/y_test[i:i+1][0],2))+'%')

预测： [5.3208866] 实际： [7.2] 差值： 1.8791133880615236 误差占比： 26.1%
预测： [15.418316] 实际： [18.8] 差值： 3.381684112548829 误差占比： 17.99%
预测： [18.811136] 实际： [19.] 差值： 0.18886375427246094 误差占比： 0.99%
预测： [32.229134] 实际： [27.] 差值： 5.229133605957031 误差占比： 19.37%
预测： [20.516674] 实际： [22.2] 差值： 1.6833259582519524 误差占比： 7.58%
预测： [16.938406] 实际： [24.5] 差值： 7.561594009399414 误差占比： 30.86%
预测： [23.801857] 实际： [31.2] 差值： 7.398143005371093 误差占比： 23.71%
预测： [20.19571] 实际： [22.9] 差值： 2.7042907714843736 误差占比： 11.81%
预测： [16.78597] 实际： [20.5] 差值： 3.714029312133789 误差占比： 18.12%
预测： [15.736834] 实际： [23.2] 差值： 7.463166427612304 误差占比： 32.17%
预测： [14.517115] 实际： [18.6] 差值： 4.082885360717775 误差占比： 21.95%
预测： [14.467209] 实际： [14.5] 差值： 0.0327911376953125 误差占比： 0.23%
预测： [13.655266] 实际： [17.8] 差值： 4.144734191894532 误差占比： 23.29%
预测： [38.504288] 实际： [50.] 差值： 11.495712280273438 误差占比： 22.99%
预测： [11.815095] 实际： [20.8] 差值： 8.98490505218506 误差占比： 43.2%
预测： [18.215858] 实际： [24.3] 差值： 6.0841415405273445 误差占比： 25.04%
预测： [22.4630